apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod
spec:
  containers:
  - name: python
    image: hmicael/python:3.11-my
    command: 
    - "sleep"
    args: 
    - "99d"
  - name: sonar
    image: sonarsource/sonar-scanner-cli:latest
    command: 
    - "sleep"
    args: 
    - "99d"
  - name: docker
    image: docker:24
    command:
      - cat
    tty: true